#!/usr/bin/env node
/**
 * PITCHATON — regenerate supabase-migrate.sql from supabase-schema.sql.
 *
 *   npm run sync:sql
 *
 * WHY THIS EXISTS
 * ---------------
 * Two SQL files ship with the project:
 *
 *   supabase-schema.sql   creates everything (fresh project)
 *   supabase-migrate.sql  drops the PITCHATON tables left behind by the old
 *                         single-file prototype, then creates everything
 *
 * The migration file must stay byte-identical to the schema file *after* its
 * "drop" phase. If someone edited one and not the other — a bucket policy, an
 * index, a new column — a project would end up subtly less locked down than the
 * code expects, and nothing would visibly fail. So the migration is generated,
 * never hand-edited: this script is the single source of drift protection.
 *
 * Run it after any change to supabase-schema.sql and commit both files.
 */

import fs from 'fs';
import path from 'path';

const root = path.resolve(import.meta.dirname, '..');
const schemaPath = path.join(root, 'supabase-schema.sql');
const migratePath = path.join(root, 'supabase-migrate.sql');

const schema = fs.readFileSync(schemaPath, 'utf8').trimEnd();

/* Objects the old prototype may have created. Order matters: children first so
 * the drops succeed even without CASCADE semantics on foreign keys. */
const LEGACY_TABLES = [
  'results',
  'files',
  'founders',
  'hub_news',
  'email_log',
  'pitches',
  'admin_settings',
  'users',
];

const header = `-- ============================================================================
-- PITCHATON — migrate an EXISTING Supabase project  (one paste, one Run)
-- ============================================================================
--
--   ⚠️  THIS FILE DROPS AND REBUILDS THE PITCHATON TABLES.
--
-- Auto-generated by \`npm run sync:sql\` from supabase-schema.sql — do not edit
-- by hand. The schema is reproduced verbatim in step 2, so a single paste is
-- all that is needed; you do NOT have to run supabase-schema.sql afterwards.
--
-- WHEN TO USE THIS INSTEAD OF supabase-schema.sql
-- -----------------------------------------------
-- Only when the project already contains objects from the earlier single-file
-- prototype (tables named pitches, founders, files, results, hub_news,
-- admin_settings, users or email_log). On a fresh project use
-- supabase-schema.sql — it will not delete anything.
--
-- WHAT IS NOT TOUCHED
-- -------------------
-- Supabase Auth users (auth.users), Storage objects, and any unrelated table of
-- yours. Only the eight PITCHATON tables, the leaderboard view and the
-- PITCHATON functions/sequence are dropped.
--
-- STEP 0 — LOOK BEFORE YOU DROP (optional, recommended)
-- ----------------------------------------------------
-- Run this query on its own first. Any count above zero is data that step 1
-- will permanently delete. If submissions matter, export each table from the
-- Table Editor (Export → CSV) before continuing.
--
--   select 'pitches' as tbl,        count(*) from public.pitches
--   union all select 'founders',    count(*) from public.founders
--   union all select 'files',       count(*) from public.files
--   union all select 'results',     count(*) from public.results
--   union all select 'hub_news',    count(*) from public.hub_news
--   union all select 'admin_settings', count(*) from public.admin_settings
--   union all select 'users',       count(*) from public.users;
-- ============================================================================


-- ----------------------------------------------------------------------------
-- STEP 1 — drop the PITCHATON objects from the earlier build
-- ----------------------------------------------------------------------------
drop view if exists public.leaderboard cascade;

${LEGACY_TABLES.map((table) => `drop table if exists public.${table.padEnd(14)} cascade;`).join('\n')}

drop function if exists public.assign_pitch_code() cascade;
drop function if exists public.touch_updated_at()  cascade;
drop sequence if exists public.pitch_code_seq      cascade;
`;

const banner = `
-- ----------------------------------------------------------------------------
-- STEP 2 — rebuild in the PITCHATON shape
-- ----------------------------------------------------------------------------
-- Everything below is supabase-schema.sql, verbatim and idempotent: it creates
-- the eight tables, the indexes, the pitch-code sequence and triggers, the
-- public leaderboard view, row level security with deny-all policies, and the
-- private pitch-files storage bucket.
-- ----------------------------------------------------------------------------
`;

fs.writeFileSync(migratePath, `${header}${banner}\n${schema}\n`);

/* ---------------------------------------------------------------- summary --- */
const files = { 'supabase-schema.sql': schema, 'supabase-migrate.sql': fs.readFileSync(migratePath, 'utf8') };
const count = (haystack, pattern) => (haystack.match(pattern) || []).length;

const report = [
  ['tables created', /create table if not exists public\.\w+/gi],
  ['indexes created', /create index if not exists \w+/gi],
  ['RLS enabled', /enable row level security/gi],
  ['storage policies', /create policy "pitch_files_/gi],
  ['bucket definition', /insert into storage\.buckets/gi],
  ['leaderboard view', /create or replace view public\.leaderboard/gi],
];

console.log(`\n  regenerated  supabase-migrate.sql  (${fs.statSync(migratePath).size} bytes)\n`);
console.log('  object            schema   migrate');
for (const [label, pattern] of report) {
  const a = count(files['supabase-schema.sql'], pattern);
  const b = count(files['supabase-migrate.sql'], pattern);
  console.log(`  ${label.padEnd(16)} ${String(a).padStart(6)}   ${String(b).padStart(7)}`);
}

/* The migration must contain every object the schema creates. RLS lines and
 * table/index creations are the parts that would silently degrade security or
 * break queries if they drifted, so fail loudly rather than print a warning. */
const mustMatch = [
  [/create table if not exists public\.\w+/gi, 'tables'],
  [/create index if not exists \w+/gi, 'indexes'],
  [/enable row level security/gi, 'RLS statements'],
  [/create policy "pitch_files_\w+"/gi, 'storage policies'],
  [/insert into storage\.buckets/gi, 'bucket definition'],
];

const problems = mustMatch
  .map(([pattern, label]) => [label, count(schema, pattern), count(files['supabase-migrate.sql'], pattern)])
  .filter(([, a, b]) => a !== b);

if (problems.length) {
  console.error('\n✗ Migration does not match the schema:');
  for (const [label, a, b] of problems) console.error(`    ${label}: schema ${a}, migrate ${b}`);
  process.exit(1);
}

console.log('\n✓ Migration contains every object the schema creates.\n');
